name: moxi
description: The Best ChatGPT Mobile Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  stacked: ^2.3.13
  stacked_services: ^0.9.2
  stacked_themes: ^0.3.9
  stacked_hooks: ^0.2.2
  flutter_hooks: ^0.18.3

  #HTTP REQUESTS
  http:

  #FIRESTORE/FIREBASE
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.5
  firebase_auth_oauth: ^1.1.0
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  cloud_functions: ^3.2.4
  cloud_firestore: ^3.1.5
  firebase_database: ^9.0.15
  firebase_app_check: ^0.0.6+16

  #ANALYTICS
  firebase_analytics: ^9.0.5

  #SOCIAL DEPENDENCIES
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^4.4.0

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async:

  #PHONE UTILITIES
  url_launcher: ^6.0.3
  share: ^2.0.1
  permission_handler: ^9.2.0
  app_settings: ^4.1.1
  shared_preferences: ^2.0.5
  wakelock: ^0.6.0+1
  devicelocale: ^0.5.0
  flutter_local_notifications: ^9.2.0
  path_provider: ^2.0.2

  #IMAGES
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.8.4+4
  flutter_image_compress: ^1.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  image: ^3.0.2

  #LOCATION
  location: ^4.3.0
  geolocator: ^8.0.1
  geocode: ^1.0.1
  geoflutterfire2: ^2.3.11
  google_place: ^0.4.0
  google_maps_webservice: ^0.0.20-nullsafety.4
  google_maps_flutter: ^2.1.7
  maps_launcher: ^2.0.0

  #DATE & TIME
  flutter_calendar_carousel: ^2.1.0
  add_2_calendar: ^2.1.2

  #UI
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0

  #REMOVE STRIPE SDK
  stripe_sdk: ^5.0.0-nullsafety.0
  flutter_inapp_purchase: ^5.0.1

  #SECURTIY
  encrypt: ^5.0.1
  crypto: ^3.0.2
  crypton: ^2.0.3
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator: ^0.6.2
  analyzer: ^3.1.0
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterThin.ttf
          weight: 100
        - asset: assets/fonts/InterExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterBlack.ttf
          weight: 900
